# Generated by Django 3.1.1 on 2020-10-23 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20201023_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=328, verbose_name='ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 18, 52, 50, 348127, tzinfo=utc)),
        ),
    ]
